sonar.projectKey=homeease-notification-service
sonar.projectName=HomeEase Notification Service
sonar.projectBaseDir=notification-service
sonar.newCode.referenceBranch=main
sonar.sources=.
sonar.exclusions=node_modules/**,logs/**,*.md,Dockerfile,.dockerignore
sonar.sourceEncoding=UTF-8
sonar.scm.provider=git
