sonar.projectKey=homeease-frontend
sonar.projectName=HomeEase Frontend
sonar.sources=src
sonar.exclusions=node_modules/**,dist/**,build/**,coverage/**,**/*.test.js,**/*.test.jsx
sonar.scm.provider=git
