sonar.projectKey=homeease
sonar.projectName=HomeEase
sonar.sources=backend,admin-backend,frontend

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/*.test.js

sonar.cpd.exclusions=**/models/**,**/middleware/**
