sonar.projectKey=homeease-admin-frontend
sonar.projectName=HomeEase Admin Frontend
sonar.projectBaseDir=admin-frontend
sonar.newCode.referenceBranch=main
sonar.sources=src
sonar.exclusions=node_modules/**,dist/**,build/**,coverage/**,**/*.test.js,**/*.test.jsx
sonar.sourceEncoding=UTF-8
sonar.scm.provider=git
