const NOTIFICATION_TYPES = Object.freeze({
  BOOKING_CREATED: "BOOKING_CREATED",
  BOOKING_CONFIRMED: "BOOKING_CONFIRMED",
  BOOKING_CANCELLED: "BOOKING_CANCELLED",
  BOOKING_COMPLETED: "BOOKING_COMPLETED",
  PAYMENT_SUCCESS: "PAYMENT_SUCCESS",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  EMERGENCY_CREATED: "EMERGENCY_CREATED",
  EMERGENCY_ASSIGNED: "EMERGENCY_ASSIGNED",
  EMERGENCY_RESOLVED: "EMERGENCY_RESOLVED",
  PROFESSIONAL_ASSIGNED: "PROFESSIONAL_ASSIGNED"
});

const NOTIFICATION_CHANNELS = Object.freeze({
  EMAIL: "Email",
  SMS: "SMS",
  PUSH: "Push Notification"
});

const NOTIFICATION_STATUS = Object.freeze({
  PENDING: "Pending",
  SUCCESS: "Success",
  FAILURE: "Failure"
});

module.exports = {
  NOTIFICATION_TYPES,
  NOTIFICATION_CHANNELS,
  NOTIFICATION_STATUS
};
