sonar.projectKey=homeease-payment-service
sonar.projectName=HomeEase Payment Service
sonar.projectBaseDir=payment-service
sonar.newCode.referenceBranch=main
sonar.sources=.
sonar.exclusions=node_modules/**,logs/**,*.md,Dockerfile,.dockerignore
sonar.sourceEncoding=UTF-8
sonar.scm.provider=git
