sonar.projectKey=admin-backend
sonar.projectName=HomeEase Admin Backend
sonar.sources=.
sonar.exclusions=node_modules/**,__tests__/**,coverage/**,logs/**,*.md,Dockerfile,.dockerignore
sonar.tests=__tests__
sonar.test.inclusions=__tests__/**/*.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
